### PR TITLE
Limit deploy to prod or *-staging

### PR DESCRIPTION
**Pull request by dineshg13**
Limit the deploy to `prod` or `*-staging`

### CODE REVIEW

**Review by songy23 — APPROVED** [review]
Can you add a description on what is being limited?

**Comment by dineshg13** [comment]
It limits the deploy to `prod` or `*-staging` . There is no change for developer workflow.

**Comment by songy23** [comment]
I think you also limit the deploy to only when PRs are merged?

E.g commits to WIP PRs like https://github.com/DataDog/opentelemetry-collector-contrib/pull/3879 shouldn't be deployed

**Comment by dineshg13** [comment]
Yes. That is the goal. We don't want to deploy without a PR review

**Pull request merged**
